# Generated by Django 4.1.5 on 2023-04-30 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_creditcard_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='last_name',
        ),
    ]
