# Generated by Django 4.1.5 on 2023-05-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_first_name_creditcard_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
